version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_tms
    volumes:
      - ./appmanager:/appmanager
    ports:
      - 8000:8000
    env_file:
      - db_keys.txt
    depends_on:
      - db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: bash -c "gunicorn -w 9 src.wsgi:application -b 0.0.0.0:8000"



  db:
    image: postgres
    container_name: postgres_tms
    env_file:
      - db_keys.txt
    volumes:
      - ./backups:/backups
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5